Upgrade dry-core
dry-rb/dry-rails pull request #57
Opened 2022-12-16 14:11 UTC by alex-lairan

dry-rails does not work with dry-core version >1.0

This change the version of dry-core and stay up to date.

2022-12-17 16:13 UTC, solnic requested changes

2022-12-17 16:13 UTC, solnic commented on dry-rails.gemspec
> +  spec.add_runtime_dependency "dry-system", ">= 1.0"
Please change this in project.yml instead and set it to `~ 1.0', '< 2'

2022-12-24 11:11 UTC, solnic commented
Closing as I addressed all of the updates via #59

2022-12-24 11:11 UTC, closed without merging

2022-12-24 11:46 UTC, alex-lairan commented
Ok, thanks!

Didn't had machine for this change :/

Merry Christmas ⛄